# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01fa5a506c25e406cf91ca6914d03c2d08fa2f0736ff5bf3410f6f10850e4490ce6c1973b010cc192e5bbaa726f590be5f6d26d5f91647cbbeae5aa1a61f362

test:
  secret_key_base: 145d124e3b4ed1fc9776b089907850e77ef85839fcf5ae00da57791fff2148b617b43e6d99ad36f22a1159476869efbde642e4fa0440744e827356b05f1aaa08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
